### ISSUE TITLE
inspired by this library - new rust playground project

### ISSUE THREAD

**Issue by RustyJoeM** [rsitko92/netconf-client#1]
Hello,

i wanted to let you know that I read your crate/library codebase, and used some of its patterns as an inspiration for implementation of my Rust `NETCONF client playground` sub-crate located at https://github.com/RustyJoeM/netconf-client-playground
I added a reference to this repository in the main readme file.

best regards,
Jozef

**Comment by r-sitko** [comment]
Hello,
Cool, I am happy that my code will be helpful for somebody.
Good luck!
